### ISSUE TITLE
Allow Maintenance Windows with open end with the mwcal command

### ISSUE THREAD

**Issue by hailpis1** [am-napier/itsi_toolbox#4]
Currently maintenance windows created with the `mwcal` command need a defined end. However ITSI allows maintenance windows without a specified end date. So it would be cool if the `mwcal` command would support this.

**Comment by am-napier** [comment]
Sorry for the delay, stopped looking here for a while but I'm back.
Don't ask me why but using end=2147385600 sets it infinite, add or subtract 1 from that and it sets a hard limit.  I'll update though to allow 0 as infinite.  In the meantime use end=2147385600 or end=now() * 2

**Comment by am-napier** [comment]
will implement change shortly allowing end=0 as infinite

**Comment by hailpis1** [comment]
> Don't ask me why but using end=2147385600 sets it infinite, add or subtract 1 from that and it sets a hard limit. 

That is really weired - but I am fine with it :). Thank you very much for looking into this!
